<a href="https://colab.research.google.com/github/CC-Shivansh-Gupta/logistic-_reg/blob/main/ann_v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [91]:
import pandas as pd
import numpy as np
import matplotlib as plt
import copy, math

data = pd.read_csv('updated_air_quality_data.csv')
data.columns = data.columns.str.replace(' ', '_')
data
#print(type(std_data))
#print(std_data.info())

,Unique_ID,Name,Measure,Geo_Type_Name,Geo_Place_Name,Time_Period,Start_Date,Data_Value,Air_Quality_Category
0,179772,Emissions,Density,UHF42,Queens,Other,2015-01-01,0.3,Good
1,179785,Emissions,Density,UHF42,Unknown,Other,2015-01-01,1.2,Good
2,178540,General Pollution,Miles,UHF42,Unknown,Annual Average,2011-12-01,8.6,Good
3,178561,General Pollution,Miles,UHF42,Queens,Annual Average,2011-12-01,8.0,Good
4,823217,General Pollution,Miles,UHF42,Queens,Summer,2022-06-01,6.1,Good
...,...,...,...,...,...,...,...,...,...
18011,816914,General Pollution,Miles,CD,Unknown,Other,2019-01-01,12.9,Moderate
18012,816913,General Pollution,Miles,CD,Unknown,Other,2010-01-01,14.7,Moderate
18013,816872,General Pollution,Miles,UHF42,Unknown,Other,2010-01-01,43.4,Bad
18014,816832,General Pollution,Miles,UHF42,Queens,Other,2010-01-01,65.8,Bad
18015,151658,General Pollution,Miles,UHF42,Unknown,Other,2005-01-01,41.0,Bad

In [92]:
rows = data.shape[0]
cols = data.shape[1]
#print(rows, cols)

In [93]:
data.Name.describe()
#data.Name.unique()

count                 18016
unique                    4
top       General Pollution
freq                  15808
Name: Name, dtype: object

In [ ]:
def extraction(column):
  name_arr = np.empty(rows, dtype = object)
  for j in range(rows):
    name_arr[j] = data.iloc[j, column]
  #print(name_arr)
  unique_names = np.unique(name_arr)
  return name_arr, unique_names

In [94]:
name_arr = np.empty(rows, dtype = object)
for j in range(rows):
  name_arr[j] = data.loc[j, 'Name']
print(name_arr)
unique_names = np.unique(name_arr)
#unique_names

['Emissions' 'Emissions' 'General Pollution' ... 'General Pollution'
 'General Pollution' 'General Pollution']

In [95]:
def one_hot_label(arr, unique):
  arrofarr_list = []
  for j in range(len(unique)):
    arr_name = np.empty(len(arr), dtype = object)
    for i in range(len(arr)):
      arr_name[i] = arr[i]
    arrofarr_list.append(arr_name)

  arrofarr_tup = tuple(arrofarr_list)
  arrofarr = np.row_stack(arrofarr_tup)
  for j in range(len(unique)):
    for i in range(len(arr)):
      if arrofarr[j][i] == unique[j]:
        arrofarr[j][i] = '1'
      else:
        arrofarr[j][i] = '0'
  #print(arrofarr)
  return arrofarr

In [96]:
name_arrofarr = one_hot_label(name_arr, unique_names)
print(name_arrofarr)

[['0' '0' '0' ... '0' '0' '0']
 ['1' '1' '0' ... '0' '0' '0']
 ['0' '0' '1' ... '1' '1' '1']
 ['0' '0' '0' ... '0' '0' '0']]

In [97]:
#data.rename(columns={'Name': 'Name_Emissions'}, inplace = True)
#data['Name_General'] = data.loc[:, 'Name_Emissions']
#data
#data['Name_Emissions'] = data['Name_Emissions'].str.replace('Emissions', '1')
#data
#data.loc[:, 'Name_Hospi'] = name_arrofarr[3]
#data
for i in range(len(unique_names)):
  data.loc[:, unique_names[i]] = name_arrofarr[i]
data

,Unique_ID,Name,Measure,Geo_Type_Name,Geo_Place_Name,Time_Period,Start_Date,Data_Value,Air_Quality_Category,Asthma-Related,Emissions,General Pollution,Hospitalizations
0,179772,Emissions,Density,UHF42,Queens,Other,2015-01-01,0.3,Good,0,1,0,0
1,179785,Emissions,Density,UHF42,Unknown,Other,2015-01-01,1.2,Good,0,1,0,0
2,178540,General Pollution,Miles,UHF42,Unknown,Annual Average,2011-12-01,8.6,Good,0,0,1,0
3,178561,General Pollution,Miles,UHF42,Queens,Annual Average,2011-12-01,8.0,Good,0,0,1,0
4,823217,General Pollution,Miles,UHF42,Queens,Summer,2022-06-01,6.1,Good,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18011,816914,General Pollution,Miles,CD,Unknown,Other,2019-01-01,12.9,Moderate,0,0,1,0
18012,816913,General Pollution,Miles,CD,Unknown,Other,2010-01-01,14.7,Moderate,0,0,1,0
18013,816872,General Pollution,Miles,UHF42,Unknown,Other,2010-01-01,43.4,Bad,0,0,1,0
18014,816832,General Pollution,Miles,UHF42,Queens,Other,2010-01-01,65.8,Bad,0,0,1,0
18015,151658,General Pollution,Miles,UHF42,Unknown,Other,2005-01-01,41.0,Bad,0,0,1,0

In [98]:
data.Unique_ID.describe()

count     18016.000000
mean     426187.112789
std      250391.154793
min      121644.000000
25%      175300.750000
50%      410798.500000
75%      649886.250000
max      828353.000000
Name: Unique_ID, dtype: float64